### ISSUE TITLE
Allow option to begin with date other than Sunday

### ISSUE THREAD

**Issue by scurd** [PredixDev/px-calendar-picker#11]
A lot of international calendars start their weeks on Mondays. It would be nice to have this as an option within this component. We already have users in other countries asking us for this feature. Thanks!

E.g. http://bootstrap-datepicker.readthedocs.io/en/latest/options.html#weekstart

**Comment by benoitjchevalier** [comment]
Hello,

this can now be done through localization of moment.js (which is used by our component behind the scene). We've also added convenience method for localizing our local instance of moment.js in px-datetime-common 0.8.2 (just released it) and are in the process of finishing documentation, in the meantime here are the guidelines we use internally:



Some of the Predix UI components use moment.js to handle dates and time, in particular the datetime and vis components. Predix UI keeps its own version of moment.js so that an application can load any version of moment.js as well without clashing. 

The Predix UI version of moment.js can be localized through the convenience function Px.moment.changeLocale(newLocale, callback, configObject). This function can either load an out of the box locale or any custom locale (more info on both mechanism below).

Please note that when changing the moment locale previous moment objects created are not affected and might need to be recreated/updated. Components depending on moment.js will recreate their moment objects after their `language` property changes, so when localizing Predix UI components the moment locale will need to be changed *before* changing the `language` property of the component.

Load a supported locale
-----------------------

Important note: in order to be able to load those locales you need to make sure *your build includes the `momentLocale` folder from px-datetime-common*. By default the locale will be searched in the px-datetime-common/momentLocale folder but the path can be configured through the `Px.moment.localeURL` variable.

When loading a supported locale just pass one of the following locale and optionally a callback (which will be called after the locale has been effectively loaded). The configObject argument isn't needed.

Example:
Px.moment.changeLocale('fr', function() {
  console.log('moment locale changed!');
});

List of out-of-the-box supported locale:
- af
- ar-dz
- ar-kw
- ar-ly
- ar-ma
- ar-sa
- ar-tn
- ar
- az
- be
- bg
- bn
- bo
- br
- bs
- ca
- cs
- cv
- cy
- da
- de-at
- de-ch
- de
- dv
- el
- en-au
- en-ca
- en-gb
- en-ie
- en-nz
- eo
- es-do
- es
- et
- eu
- fa
- fi
- fo
- fr-ca
- fr-ch
- fr
- fy
- gd
- gl
- gom-latn
- he
- hi
- hr
- hu
- hy-am
- id
- is
- it
- ja
- jv
- ka
- kk
- km
- kn
- ko
- ky
- lb
- lo
- lt
- lv
- me
- mi
- mk
- ml
- mr
- ms-my
- ms
- my
- nb
- ne
- nl-be
- nl
- nn
- pa-in
- pl
- pt-br
- pt
- ro
- ru
- sd
- se
- si
- sk
- sl
- sq
- sr-cyrl
- sr
- ss
- sv
- sw
- ta
- te
- tet
- th
- tl-ph
- tlh
- tr
- tzl
- tzm-latn
- tzm
- uk
- ur
- uz-latn
- uz
- vi
- x-pseudo
- yo
- zh-cn
- zh-hk
- zh-tw

Because the locale needs to be fetched from a script this process is asynchronous, you can use the callback in Px.moment.changeLocale in order to perform actions after the locale has been loaded (such as updating the `language` and `resources` of the PX components).

Load a custom locale
-----------------------

Loading a custom locale is relatively straightforward, but implies manually loading/generating a config object as defined by moment.js: http://momentjs.com/docs/#/customization/

example:
Px.moment.changeLocale(null, null, yourConfigObject);

In this scenario the moment.js locale change is synchronous.


Let me know if you have more questions
