### ISSUE TITLE
not able to deselect the selection thats made

### ISSUE THREAD

**Issue by 502383987** [PredixDev/px-calendar-picker#8]
px-calendar-picker is not a mandatory field in our application screen. But a user can select the month of any year.  now if the user has changed his mind and want to deselect the selection thats made ..he is not able to do that. 

And in page to page navigation data from some other page has to be loaded to the form field components. so that way if we want to assign a date to the px-calendar-component . is that possible ?

**Comment by benoitjchevalier** [comment]
There's currently no way to "deselect" the date in calendar picker since it cannot be empty in the first place. It will always have a value. You might have to implement something on your application to enable/disable the calendar picker.

You can set the selection in the calendar picker through `singleSelectedDate` or `range` depending  on what mode you're using the calendar picker
